spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stepcapsule:3306/StepCapsule
    username: root
    password: admin
  # 超时时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
